language: ruby
cache:
  directories: random/submodule

install:
- (git clone https://github.com/file/file && cd file && autoreconf -f -i && ./configure --disable-silent-rules && make -j4 && make install)

script:
- ls -al
- file .travis.yml
- wget https://github.com/realm/realm-cocoa/releases/download/v0.98.4/Carthage.framework.zip
- unzip Carthage.framework.zip
- file Carthage/Build/iOS/Realm.framework/Realm
- file -k Carthage/Build/iOS/Realm.framework/Realm
- which file
- file --version
- file --help
